### ISSUE TITLE
An error will be reported in a concurrent scenario

### ISSUE THREAD

**Issue by zonglang** [stewartmcgown/grammarly-api#43]
As the title, the detailed error is as follows
```
throw new Error('Unable to create a session with these credentials.');      
                  ^

Error: Unable to create a session with these credentials.
    at Object.<anonymous> (E:\***\node_modules\@stewartmcgown\grammarly-api\build\lib\auth.js:138:19)
    at Generator.next (<anonymous>)
    at fulfilled (E:\***\node_modules\@stewartmcgown\grammarly-api\build\lib\auth.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
```

The reason for this error is that too many websockets have been established, has it been officially disabled by Grammarly?

**Comment by zonglang** [comment]
The response is：
```
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],       
      _events: [Object: null prototype],     
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],       
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://auth.grammarly.com/v3/user/oranonymous?app=firefoxExt&containerId=50SOennENtp1D8z',
    status: 429,
    statusText: 'Too Many Requests',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```
It seems that there are too many requests and they are restricted
